server.port=8081

spring.datasource.url=jdbc:postgresql://db.lysbrwlfgpjpkdlzvxwa.supabase.co:5432/postgres?user=postgres&password=sportHubproject@12
spring.datasource.username=postgres
spring.datasource.password=sportHubproject@12

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true